export const COMMAND_PREFIX = '/'
export const ERROR_MESSAGES = {
  NOT_ADMIN: 'Você não é um administrador do grupo.',
  PARTICIPANT_ADMIN: 'O alvo desse comando não pode ser um administrador.',
  BAN_ADMIN: 'Não é possível banir um administrador.',
  NOT_BANNED: 'Não foi possível banir este número do grupo.',
  NOT_FOUND: 'Este número não foi encontrado no grupo.',
  NO_VCARD: 'Você deve responder a uma mensagem de contato para adicionar um novo membro.',
  ALREADY_EXISTS: 'O número já está no grupo.',
  ADD_DIRECTLY: 'Não foi possível adicionar esse número diretamente ao grupo. Um convite foi enviado mas ainda pode ser recusado.',
  SELF_ADM_RESTRICTED: 'Você não pode executar este comando em seu próprio número.',
  BRAZIL_ONLY: 'Somente números brasileiros são permitidos nesse grupo.',
  INVALID_NUMBER: 'O número informado é inválido.',
  UNKNOWN: 'Ocorreu um erro durante a execução do comando.',
  METHOD_NOT_ALLOWED: 'Esse comando não pode ser realizado dessa forma.',
  REPLY: 'Para usar esse comando você deve obrigatoriamente responder a uma mensagem no grupo',
  DESCRIPTION: 'Não foi possível atualizar a descrição deste grupo.',
  NOT_ENABLED: 'Não foi possível habilitar este comando.',
  NOT_DISABLED: 'Não foi possível desabilitar este comando.',
  LINK_NOT_CREATED: 'Não foi possível criar um novo link de convite para este grupo',
  PARTICIPANT_NOT_MUTED: 'Não foi possível mutar este número no grupo',
  PARTICIPANT_NOT_UNMUTED: 'Não foi possível desmutar este número.',
  STATUS_NOT_FOUND: 'Nenhuma mensagem de status foi encontrada.',
  ARGS: 'Não foi possível executar esse comando, você deve fornecer mais informações após o comando registrado.',
  FORBIDDEN: 'Essa ação é proibida.',
  GROUP_NOT_FOUND: 'Grupo não encontrado.'
}
export const SUCCESS_MESSAGES = {
  BAN: 'Número banido com sucesso.',
  ADD: 'Número adicionado com sucesso.',
  ADM_DEMOTE: 'Administrador removido com sucesso.',
  ADM_PROMOTE: 'Administrador adicionado com sucesso.',
  UPDATE_DESCRIPTION: 'Descrição atualizada com sucesso',
  COMMAND_ENABLED: 'Comando habilitado com sucesso!',
  COMMAND_DISABLED: 'Comando desabilitado com sucesso!',
  PARTICIPANT_MUTED: 'Número mutado com sucesso',
  PARTICIPANT_UNMUTED: 'Agora este número pode enviar mensagens novamente.',
  LINK_REVOKED: 'Link do grupo revogado, um novo link foi gerado.',
  STATUS_UPDATED: 'O status do bot foi atualizado com sucesso.',
  WELCOME_MESSAGE: 'Mensagem de boas-vindas atualizada com sucesso',
  ON: "Recurso ativado",
  OFF: "Recurso desativado",
}
export const INVITE_TEMPLATE = (subject: string, groupInvite: string) => `Você foi convidado para o grupo ${subject}.\nhttps://chat.whatsapp.com/${groupInvite}`
