const express = require("express");
const router = express.Router();
const instanceRoutes = require("./instance.route");
const messageRoutes = require("./message.route");
const miscRoutes = require("./misc.route");
const groupRoutes = require("./group.route");
const authRoutes = require("./auth.route");
router.get("/status", (req, res) => res.send("OK"));
router.use("/instance", instanceRoutes);
router.use("/message", messageRoutes);
router.use("/group", groupRoutes);
router.use("/misc", miscRoutes);
router.use("/auth", authRoutes);
module.exports = router;
