const express = require("express");
const controller = require("../controllers/instance.controller");
const keyVerify = require("../middlewares/keyCheck");
const loginVerify = require("../middlewares/loginCheck");
const verifyJwt = require("../middlewares/verifyJwt");
const router = express.Router();
router.route("/init").get(controller.init);
router.route("/qr").get(verifyJwt, controller.qr);
router.route("/qrbase64").get(verifyJwt, controller.qrbase64);
router.route("/info").get(verifyJwt, controller.info);
router.route("/restore").get(controller.restore);
router.route("/logout").delete(keyVerify, loginVerify, controller.logout);
router.route("/delete").delete(verifyJwt, controller.delete);
router.route("/list").get(controller.list);
router.route("/pairCode").post(verifyJwt, controller.pairCode);
module.exports = router;
